name: Image Builder

on:
  label:
    types:
      - created
  push:
    branches:
      - main
  issues:
    types:
      - opened
      - labeled

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repo to get tools version
        uses: actions/checkout@master
        with: 
          repository: phosae/critools-image
          path: ./critools-image

      - name: make arch dir
        run: |
          mkdir ./critools-image/amd64 && mkdir ./critools-image/arm64

      - name: Put version to env
        run: |
          echo "VERSION=$(cat ./critools-image/VERSION)" >> $GITHUB_ENV

      - name: Show VERSION
        run: |
          echo "critools VERSION: ${{env.VERSION}}"

      - name: download cri tools
        run: |
          wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${{env.VERSION}}/crictl-$VERSION-linux-amd64.tar.gz && wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${{env.VERSION}}/crictl-$VERSION-linux-arm64.tar.gz && wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/critest-${{env.VERSION}}-linux-amd64.tar.gz && wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/critest-${{env.VERSION}}-linux-arm64.tar.gz

      - name: extract crictl
        run: |
          tar -zxvf crictl-${{env.VERSION}}-linux-amd64.tar.gz -C ./critools-image/amd64 &&  tar -zxvf crictl-${{env.VERSION}}-linux-arm64.tar.gz -C ./critools-image/arm64
      - name: extract critest    
        run: |
          tar -zxvf critest-${{env.VERSION}}-linux-amd64.tar.gz -C ./critools-image/amd64 && tar -zxvf critest-${{env.VERSION}}-linux-arm64.tar.gz -C ./critools-image/arm64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: zengxu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub 
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./critools-image
          # Note: tags has to be all lower-case
          tags: |
            zengxu/critools:${{ env.VERSION }} 
          platforms: |
            linux/amd64,linux/arm64
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
